name: CI Pipeline
on: [push]

jobs:
    build:
        runs-on: ubuntu-lastes
        steps:
            - users: actions/checkout@v4
            - name: Run a script
               run: echo "Hello, Github Actions!" 
